### ISSUE TITLE
Neither the property "redirect" nor one of the methods "redirect()", "getredirect()"/"isredirect()" or "__call()" exist and have public access in class "Symfony\Component\HttpKernel\DataCollector\RequestDataCollector" in @WebProfiler/Profiler/layout.html.twig at line 23.

### ISSUE THREAD

**Issue by EmyJ** [silexphp/Silex-WebProfiler#101]
Hi,

I just update to Symfony 2.8 and i have a bug with the WebProfiler.
I can access to my web page but the profiler wont load and throw this error:

_Neither the property "redirect" nor one of the methods "redirect()", "getredirect()"/"isredirect()" or "__call()" exist and have public access in class "Symfony\Component\HttpKernel\DataCollector\RequestDataCollector" in @WebProfiler/Profiler/layout.html.twig at line 23._

Here is my composer.json

 "name": "symfony/framework-standard-edition",
    "license": "MIT",
    "type": "project",
    "description": "The \"Symfony Standard Edition\" distribution",
    "autoload": {
        "psr-0": { "": "src/" }
    },
    "require": {
        "php": ">=5.5.9",
        "symfony/symfony": "2.8.*",
        "doctrine/orm": "~2.4",
        "doctrine/doctrine-bundle": "~1.4",
        "doctrine/doctrine-fixtures-bundle": "~2.2",
        "twig/extensions": "~1.0",
        "symfony/assetic-bundle": "~2.8",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~4.0",
        "sensio/framework-extra-bundle": "~3.0",
        "sensio/generator-bundle": "~2.3",
        "incenteev/composer-parameter-handler": "~2.0",
        "symfony/icu": "1.0.*@dev",
        "gedmo/doctrine-extensions": "dev-master",
        "white-october/pagerfanta-bundle": "dev-master",
        "friendsofsymfony/user-bundle": "~2.0@dev",
        "fp/openid-bundle": "dev-master",
        "sonata-project/admin-bundle": "~3.9",
        "sonata-project/doctrine-orm-admin-bundle": "~3.1",
        "widop/google-analytics-bundle": "*",
        "excelwebzone/recaptcha-bundle": "dev-master",
        "hwi/oauth-bundle": "0.5.*-dev",
        "lightopenid/lightopenid": "dev-master"

The subject who is already talking does not help me.  
https://github.com/silexphp/Silex-WebProfiler/issues/94

Do you have any idea ?

**Comment by SpacePossum** [comment]
Hi,
You are using Symfony however this is the project for the webprofiler of Silex. You might want to try @ the Symfony webprofiler itself: https://github.com/symfony/web-profiler-bundle
You might even get support faster if you ask in the IRC channel, http://symfony.com/support
