### ISSUE TITLE
PHP 7.0 tests broken on Travis CI due to phpunit 6.x

### ISSUE THREAD

**Issue by ek9** [silexphp/Silex-WebProfiler#111]
I've submited a PR and the tests for PHP 7.0 travis failed due to phpunit error. Checking more, I found that it's using phpunit `6.0.8`, which has updated classes.

Perhaps a solution would be to include specific version of `phpunit` in `require-dev` instead of relying on phpunit version that Travis CI has.

The tests usually run on `phpunit 4.5.x` (`4.5.0`) otherwise and pass. In the `6.x` series the class names have been updated, thus phpunit throws an error when trying to run tests.

Example: 
- Tests pass on PHP 5.x / phpunit `4.5.0`: https://travis-ci.org/silexphp/Silex-WebProfiler/jobs/219888582
- Tests fail on PHP 7.0 / phpunit `6.0.8`: https://travis-ci.org/silexphp/Silex-WebProfiler/jobs/219888583

**Comment by ek9** [comment]
Affected PR #109

**Comment by fabpot** [comment]
fixed in #113
