### ISSUE TITLE
new required package

### ISSUE THREAD

**Issue by 719media** [silexphp/Silex-WebProfiler#115]
Uncaught exception 'ReflectionException' with message 'Class Symfony\Bundle\DebugBundle\Tests\DependencyInjection\DebugExtensionTest does not exist'

this class is only in require-dev and not require, so when installing silex/web-profiler you get this error. Seems like a BC break to require a change in the root package composer.json? Or maybe I'm just using composer wrong.

**Comment by fabpot** [comment]
Which version are you using?

**Comment by 719media** [comment]
This is with latest Silex, 2.0.4, and latest web-profiler, 2.0.7. My understanding of composer is that it only uses require-dev of the root package, and not any required packages.

It looks like this commit:
https://github.com/silexphp/Silex-WebProfiler/commit/5697413447855f9c337a90713274423fc51eee7f

No longer checks for existence of file/class, and so it's assuming you are running web-profiler with debug-bundle (and down the line, phpunit/etc.) installed. Perhaps this is normal operation for most, but I was just using web-profiler without phpunit/etc., so this results in the above error since I don't have symfony/debug-bundle in my root composer.json

**Comment by fabpot** [comment]
Oops, I had a fix and forgot to push and release. 2.0.8 is out now, that should fix the issue.

**Comment by 719media** [comment]
Works like a charm now, thank you for the prompt attention
