### ISSUE TITLE
Requires PHPUnit when symfony/debug-bundle is installed

### ISSUE THREAD

**Issue by oliverwilliams84** [silexphp/Silex-WebProfiler#116]
Title. Calls Symfony\Bundle\DebugBundle\Tests\DependencyInjection\DebugExtensionTest which requires PHPUnit (which isn't stated anywhere)

1) is this intended behaviour (seems strange to call a test case from a working app)
2) can this be noted somewhere so others dont run into the same problem

**Comment by fabpot** [comment]
fixed in 2.0.9
