### ISSUE TITLE
Fatal error: Allowed memory size

### ISSUE THREAD

**Issue by Coosos** [silexphp/Silex-WebProfiler#123]
Hello,

I'm trying to include the "WebProfiler" in my silex application (2.0).
Except, that I have a mistake indicating that I exceed the memory allow.

I search everywhere, on Google and even in the sources and I do not find the problem.

Here is the execution trace
![webprofilersilex](https://user-images.githubusercontent.com/5632327/29029129-e247546e-7b86-11e7-87c6-e7a098f53bd9.png)

Composer show:
![composershowsilex](https://user-images.githubusercontent.com/5632327/29029894-80d33fba-7b89-11e7-80a3-12ead5231005.png)

Thank you for your help 😄

**Comment by fabpot** [comment]
Closing this old issue. Anyway, it's impossible to understand the issue here without more details.
