### ISSUE TITLE
WebProfiler needs to be made compatible with Symfony 4

### ISSUE THREAD

**Issue by flip111** [silexphp/Silex-WebProfiler#125]
https://github.com/silexphp/Silex-WebProfiler/blob/cd76e55490d556a81378b8230e28f55536811418/WebProfilerServiceProvider.php#L141

https://github.com/symfony/symfony/commit/860575a88240a1eca46fc9a660212816827d32df#commitcomment-25155523

`TwigDataCollector` constructor now takes an extra argument

**Comment by alehaa** [comment]
Think this was fixed in #126
