### ISSUE TITLE
When using '$app['twig']->addGlobal' - receive the error 'Template "@WebProfiler/Profiler/toolbar_js.html.twig" is not defined ().'

### ISSUE THREAD

**Issue by madebydavid** [silexphp/Silex-WebProfiler#25]
If I have the web profiler enabled and use the addGlobal feature of twig then an error occurs when loading the profiler toolbar templates.

![silex](https://f.cloud.github.com/assets/5401249/1326229/fb70eb6c-34db-11e3-84f2-1c99cf5456e8.png)

I have created a gist which demonstrates the issue - https://gist.github.com/madebydavid/6976097

If I comment out line 14 of index.php then the error does not occur. If I leave line 14 uncommented and comment out lines 19-22 inclusive (disabling the profiler) then the error does not occur.

**Comment by martinsik** [comment]
I guess the same thing is when extending `twig.loader`.

    $app['twig.loader'] = $app->share($app->extend('twig.loader', function($loader, $app) {
        $twigLoader = new \Twig_Loader_Filesystem();
        $twigLoader->addPath('/path/to/project', 'prefix');
        $loader->addLoader($twigLoader);
        return $loader;
    }));
