### ISSUE TITLE
Since Symfony 2.4.0, the "timer" and "timeline" no longer work in the Profiler.

### ISSUE THREAD

**Issue by bobdenotter** [silexphp/Silex-WebProfiler#30]
Since the upgrade to Symfony 2.4.0, the toolbar no longer lists the execution time, and the profiler timelines do not work either. As far as I can tell, this is because of the changes in `Symfony\Component\HttpKernel\DataCollector\TimeDataCollector`, but it might be something else. 

Minimal testcase: 

composer.json:

```
{
    "require": {
        "silex/silex": "~1.1",
        "silex/web-profiler": "1.0.*"
    }
}
```

index.php:

``` php
<?php

use Silex\Provider;

require_once __DIR__.'/../vendor/autoload.php';

$app = new Silex\Application();

$app['debug'] = true;

$app->register(new Provider\ServiceControllerServiceProvider());
$app->register(new Provider\TwigServiceProvider());
$app->register(new Provider\UrlGeneratorServiceProvider());

$app->register(new Provider\WebProfilerServiceProvider(), array(
    'profiler.cache_dir' => __DIR__.'/../cache/profiler',
    'profiler.mount_prefix' => '/_profiler', // this is the default
));

$app->get('/', function () {
    return "<html><body>Hi!</body></html>";
});

$app->run();
```

Result: 

![screen shot 2013-12-05 at 19 10 39](https://f.cloud.github.com/assets/1833361/1685454/98bfe8f8-5dd8-11e3-9ab1-7d67c4df0293.png)

---

![screen shot 2013-12-05 at 19 09 57](https://f.cloud.github.com/assets/1833361/1685457/9f309d22-5dd8-11e3-9ca2-81610567591b.png)

**Comment by OnekO** [comment]
This is happening to me yet... using Silex 1.* and silex/web-profiler 1.0.*. Any suggestion?
