### ISSUE TITLE
Support intercept_redirects

### ISSUE THREAD

**Issue by CSchulz** [silexphp/Silex-WebProfiler#34]
Hello,

I am trying out the web profiler support for silex and noticed that I am missing the intercept_redirects feature.
Giving as second argument true for WebDebugToolbarListener results for me in a

Twig_Error_Loader: Template "TwigBundle::layout.html.twig" is not defined ().

layout.html.twig is in this case my base template from which all other templates derives.

**Comment by futurevision** [comment]
This issue is closed but no solution seems to be provided?

Template "TwigBundle::layout.html.twig" is not defined () in "@WebProfiler/Profiler/toolbar_redirect.html.twig" at line 1.

How do I register the Twig template or can I override the entire template some how?

**Comment by dadaxr** [comment]
Got exact same problem. 

How configure twig to register that specific template ?

I tried to add the twig-bundle views folder in my twig config but without success : 

```
$app->register(new TwigServiceProvider(), array(
    'twig.class_path'       => __DIR__ . '/../vendor/twig/twig/lib',
    'twig.path'             => array(
        __DIR__ . '/views',
        __DIR__ . '/../web/content',
        __DIR__ . '/../vendor/symfony/twig-bundle/Resources/views'
    )
));
```

Any suggestion ?

**Comment by aerialls** [comment]
I've got the same problem. Someone has the solution? 

Thanks!

**Comment by ek9** [comment]
I have opened a separate issue. If you ( @dadaxr @futurevision @aerialls ) could provide any further feedback or comments how you solved it, it might help me file a PR to fix this.
