### ISSUE TITLE
The function "render" does not exist

### ISSUE THREAD

**Issue by rogerioadris** [silexphp/Silex-WebProfiler#68]
The function "render" does not exist in "@WebProfiler/Collector/config.html.twig" at line 1

Package | Version
-------- | --------
doctrine/annotations        | v1.2.4
doctrine/cache              | v1.4.1
doctrine/collections        | v1.3.0
doctrine/common             | v2.5.0
doctrine/dbal               | v2.5.1
doctrine/inflector          | v1.0.1
doctrine/lexer              | v1.0.1
monolog/monolog             | 1.13.1
pimple/pimple               | v1.1.1
psr/log                     | 1.0.0
silex/silex                 | v1.3.0
silex/web-profiler          | v1.0.7
swiftmailer/swiftmailer     | v5.4.0
symfony/config              | v2.7.0
symfony/console             | v2.7.0
symfony/debug               | v2.7.0
symfony/event-dispatcher    | v2.7.0
symfony/filesystem          | v2.7.0
symfony/form                | v2.7.0
symfony/http-foundation     | v2.7.0
symfony/http-kernel         | v2.7.0
symfony/intl                | v2.7.0
symfony/locale              | v2.7.0
symfony/options-resolver    | v2.7.0
symfony/process             | v2.7.0
symfony/property-access     | v2.7.0
symfony/routing             | v2.7.0
symfony/security            | v2.7.0
symfony/stopwatch           | v2.7.0
symfony/translation         | v2.7.0
symfony/twig-bridge         | v2.7.0
symfony/validator           | v2.7.0
symfony/web-profiler-bundle | v2.7.0
twig/twig                   | v1.18.1

does anyone know how to solve?

**Comment by fabpot** [comment]
see #67

**Comment by rogerioadris** [comment]
Thanks :)
