### ISSUE TITLE
Enable other panel

### ISSUE THREAD

**Issue by indominus** [silexphp/Silex-WebProfiler#71]
I can't find any solution to enable Security and Doctrine Panel ,just like Symfony. 
Is there any chance for litle how to enable?

**Comment by MatTheCat** [comment]
I found https://github.com/kurlltd/silex-security-profiler-provider and https://github.com/Sorien/silex-dbal-profiler but I would like to have this provider include these panels too.

**Comment by HeahDude** [comment]
I think we can close this issue in favor of #19 since the security panel is now supported in master/2.0 by adding the security bundle in the dependencies (ref 4a3d3cc61e7b57f06912698515ac63396fcee19c).
