### ISSUE TITLE
Missing token?

### ISSUE THREAD

**Issue by flip111** [silexphp/Silex-WebProfiler#83]
When i enable this provider i get

```
Some mandatory parameters are missing ("token") to generate a URL for route "_profiler_router".
```

Without it everything works fine

**Comment by ek9** [comment]
Can you provide any more details? I have experienced this with the recent version(s). Otherwise if there is no more data (i.e. versions used or `composer.json`, I would suggest to close this as it's hard to debug).

**Comment by flip111** [comment]
Silex version was HEAD at the time of writing. You experienced this problem too with recent versions?

**Comment by ek9** [comment]
Sorry, my previous comment was misleading. I meant to say I haven't experienced this. If this was on `HEAD` (non-released), then perhaps this got fixed already?

**Comment by flip111** [comment]
I don't know how to reproduce this error anymore 1 year later. I just tested on a fresh silex project and it seems to work fine. I will reopen in case i run into this issue again.
