### ISSUE TITLE
Support symfony 3.1

### ISSUE THREAD

**Issue by mvanbaak** [silexphp/Silex-WebProfiler#92]
https://github.com/silexphp/Silex-WebProfiler/pull/91

**Comment by mvanbaak** [comment]
https://github.com/symfony/symfony/pull/17589 introduced forward/redirect tracking.
But it breaks with this webprofiler. I'm not sure what the best way to solve this.
For this, I left the web-profiler-bundle at 3.0.*

**Comment by fabpot** [comment]
@HeahDude Can you have a look at it?

**Comment by mvanbaak** [comment]
The PR for the symfony web-profiler-bundle introduces src/Symfony/Bundle/FrameworkBundle/DataCollector/RequestDataCollector.php, specifically the getForward() method there. It's missing if you are not using the FrameworkBundle (as is the case with silex)
As soon as I update the web-profiler-bundle to 3.1 the unit tests fail because it cannot find this method (of course).

**Comment by HeahDude** [comment]
@mvanbaak Thank you for reporting this. I've opened https://github.com/symfony/symfony/pull/18959 that fixes it.

**Comment by mvanbaak** [comment]
Thank you :)
