### ISSUE TITLE
Profiler ajax call returning 35k lines of html

### ISSUE THREAD

**Issue by kfholbrook** [silexphp/Silex-WebProfiler#93]
The profiler's ajax call takes about 30 secs to complete, when it completes it returns a 500 error and about 35k lines of html. The html consist of one page of the project over and over again, 150 times. No matter where I navigate in this project I get the same response from the profiler with the same html. 

I've cleared the twig cache and profiler cache and get the same result. I'm happy to post any code that would help.

**Comment by ek9** [comment]
Hi,

could you provide your `composer.json` and `web/index.php` (or other relevant app bootstrap files) so we can reproduce this?

**Comment by fabpot** [comment]
Closing as there is no feedback.
